services:
  reports-mysql:
    image: mysql:8.4
    container_name: msreports-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT:-3309}:3309'
    volumes:
      - msreports_mysql:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-p${DB_PASSWORD}']
      interval: 10s
      timeout: 5s
      retries: 10

  reports-api:
    image: msreports-api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: msreports-api
    depends_on:
      reports-mysql:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__Default: 'server=reports-mysql;port=3306;database=${DB_NAME};user=${DB_USER};password=${DB_PASSWORD};TreatTinyAsBoolean=false'
    ports:
      - '${API_HOST_PORT:-8083}:8083'

volumes:
  msreports_mysql:
# Para usar un archivo de entorno espec√≠fico:
#   docker compose --env-file .env.development up
#   docker compose --env-file .env.production up
